-- ============================================================
-- 03_cleanup.sql
-- Tear everything down after the demo.
-- ============================================================

USE ROLE DCM_DEVELOPER;
EXECUTE DCM PROJECT DCM_DEMO_ADMIN.PROJECTS.SUPPORT_ANALYTICS_DEMO PURGE;
DROP DCM PROJECT IF EXISTS DCM_DEMO_ADMIN.PROJECTS.SUPPORT_ANALYTICS_DEMO;
DROP DATABASE IF EXISTS DCM_DEMO_ADMIN;

USE ROLE ACCOUNTADMIN;
DROP INTEGRATION IF EXISTS GITHUB_API_INTEGRATION;
DROP DATABASE IF EXISTS GITHUB_INTEGRATION;  -- contains the PAT secret
DROP ROLE IF EXISTS DCM_DEVELOPER;
